# set board part
create_project rtl_kernel /home/u55c/jeffliao/nop/rtl_kernel/rtl_kernel -part xcu55c-fsvh2892-2L-e

set_property board_part xilinx.com:au55c:part0:1.0 [current_project]
add_files -norecurse {/home/u55c/jeffliao/nop/src/IP/core.sv /home/u55c/jeffliao/nop/src/IP/control_s_axi.sv /home/u55c/jeffliao/nop/src/IP/instructionQueue.sv /home/u55c/jeffliao/nop/src/IP/highPrecEngine.sv /home/u55c/jeffliao/nop/src/IP/write_bridge.sv /home/u55c/jeffliao/nop/src/IP/vvd_top.sv /home/u55c/jeffliao/nop/src/IP/asic_top.sv /home/u55c/jeffliao/nop/src/IP/controller.sv /home/u55c/jeffliao/nop/src/IP/fake_DW02_tree.v /home/u55c/jeffliao/nop/src/IP/ram.sv /home/u55c/jeffliao/nop/src/IP/read_bridge.sv /home/u55c/jeffliao/nop/src/IP/accumulator.sv /home/u55c/jeffliao/nop/src/IP/vectorEngine.sv /home/u55c/jeffliao/nop/src/IP/fifo.sv}
update_compile_order -fileset sources_1


# package ip for vitis
ipx::package_project -root_dir ./rtl_kernel/rtl_kernel.srcs/sources_1/imports/IP -vendor user.org -library user -taxonomy /UserIP
set_property vendor jeffliao [ipx::current_core]
set_property ipi_drc {ignore_freq_hz false} [ipx::current_core]
set_property sdx_kernel true [ipx::current_core]
set_property sdx_kernel_type rtl [ipx::current_core]
set_property vitis_drc {ctrl_protocol ap_ctrl_hs} [ipx::current_core]
set_property vitis_drc {ctrl_protocol user_managed} [ipx::current_core]
set_property ipi_drc {ignore_freq_hz true} [ipx::current_core]

# set associated clock for each interface
ipx::associate_bus_interfaces -busif m00_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m01_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m02_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m03_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m04_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m05_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m06_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m07_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m08_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m09_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m10_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m11_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m12_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m13_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m14_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m15_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m16_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m17_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m18_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m19_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m20_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m21_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m22_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m23_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m24_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m25_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m26_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m27_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m28_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m29_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m30_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif m31_axi        -clock ap_clk [ipx::current_core]
ipx::associate_bus_interfaces -busif s_axi_control  -clock ap_clk [ipx::current_core]

# add register for axilite control
ipx::add_register User_Control          [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm00_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm01_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm02_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm03_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm04_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm05_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm06_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm07_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm08_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm09_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm10_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm11_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm12_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm13_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm14_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm15_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm16_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm17_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm18_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm19_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm20_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm21_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm22_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm23_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm24_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm25_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm26_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm27_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm28_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm29_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm30_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm31_read_base_addr  [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm00_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm01_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm02_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm03_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm04_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm05_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm06_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm07_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm08_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm09_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm10_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm11_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm12_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm13_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm14_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm15_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm16_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm17_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm18_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm19_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm20_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm21_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm22_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm23_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm24_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm25_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm26_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm27_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm28_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm29_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm30_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register hbm31_write_base_addr [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]

ipx::add_register instruction_base      [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]
ipx::add_register instruction_num       [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]

# edit offset
set_property address_offset 0x010  [ipx::get_registers User_Control          -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x01c  [ipx::get_registers hbm00_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x024  [ipx::get_registers hbm01_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x02c  [ipx::get_registers hbm02_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x034  [ipx::get_registers hbm03_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x03c  [ipx::get_registers hbm04_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x044  [ipx::get_registers hbm05_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x04c  [ipx::get_registers hbm06_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x054  [ipx::get_registers hbm07_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x05c  [ipx::get_registers hbm08_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x064  [ipx::get_registers hbm09_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x06c  [ipx::get_registers hbm10_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x074  [ipx::get_registers hbm11_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x07c  [ipx::get_registers hbm12_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x084  [ipx::get_registers hbm13_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x08c  [ipx::get_registers hbm14_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x094  [ipx::get_registers hbm15_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x09c  [ipx::get_registers hbm16_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0a4  [ipx::get_registers hbm17_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0ac  [ipx::get_registers hbm18_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0b4  [ipx::get_registers hbm19_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0bc  [ipx::get_registers hbm20_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0c4  [ipx::get_registers hbm21_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0cc  [ipx::get_registers hbm22_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0d4  [ipx::get_registers hbm23_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0dc  [ipx::get_registers hbm24_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0e4  [ipx::get_registers hbm25_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0ec  [ipx::get_registers hbm26_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0f4  [ipx::get_registers hbm27_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x0fc  [ipx::get_registers hbm28_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x104  [ipx::get_registers hbm29_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x10c  [ipx::get_registers hbm30_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x114  [ipx::get_registers hbm31_read_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

set_property address_offset 0x11c  [ipx::get_registers hbm00_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x124  [ipx::get_registers hbm01_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x12c  [ipx::get_registers hbm02_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x134  [ipx::get_registers hbm03_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x13c  [ipx::get_registers hbm04_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x144  [ipx::get_registers hbm05_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x14c  [ipx::get_registers hbm06_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x154  [ipx::get_registers hbm07_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x15c  [ipx::get_registers hbm08_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x164  [ipx::get_registers hbm09_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x16c  [ipx::get_registers hbm10_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x174  [ipx::get_registers hbm11_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x17c  [ipx::get_registers hbm12_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x184  [ipx::get_registers hbm13_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x18c  [ipx::get_registers hbm14_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x194  [ipx::get_registers hbm15_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x19c  [ipx::get_registers hbm16_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1a4  [ipx::get_registers hbm17_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1ac  [ipx::get_registers hbm18_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1b4  [ipx::get_registers hbm19_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1bc  [ipx::get_registers hbm20_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1c4  [ipx::get_registers hbm21_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1cc  [ipx::get_registers hbm22_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1d4  [ipx::get_registers hbm23_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1dc  [ipx::get_registers hbm24_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1e4  [ipx::get_registers hbm25_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1ec  [ipx::get_registers hbm26_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1f4  [ipx::get_registers hbm27_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x1fc  [ipx::get_registers hbm28_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x204  [ipx::get_registers hbm29_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x20c  [ipx::get_registers hbm30_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x214  [ipx::get_registers hbm31_write_base_addr  -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

set_property address_offset 0x21c  [ipx::get_registers instruction_base       -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property address_offset 0x220  [ipx::get_registers instruction_num        -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

# edit register size
set_property size 32 [ipx::get_registers User_Control           -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm00_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm01_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm02_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm03_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm04_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm05_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm06_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm07_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm08_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm09_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm10_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm11_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm12_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm13_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm14_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm15_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm16_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm17_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm18_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm19_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm20_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm21_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm22_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm23_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm24_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm25_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm26_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm27_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm28_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm29_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm30_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm31_read_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

set_property size 64 [ipx::get_registers hbm00_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm01_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm02_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm03_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm04_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm05_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm06_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm07_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm08_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm09_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm10_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm11_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm12_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm13_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm14_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm15_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm16_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm17_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm18_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm19_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm20_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm21_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm22_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm23_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm24_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm25_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm26_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm27_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm28_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm29_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm30_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 64 [ipx::get_registers hbm31_write_base_addr   -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

set_property size 32 [ipx::get_registers instruction_base        -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property size 32 [ipx::get_registers instruction_num         -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

# edit register description
set_property description {User Control}     [ipx::get_registers User_Control            -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm00_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm01_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm02_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm03_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm04_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm05_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm06_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm07_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm08_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm09_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm10_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm11_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm12_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm13_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm14_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm15_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm16_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm17_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm18_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm19_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm20_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm21_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm22_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm23_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm24_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm25_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm26_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm27_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm28_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm29_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm30_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm31_read_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

set_property description {Pointer argument} [ipx::get_registers hbm00_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm01_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm02_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm03_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm04_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm05_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm06_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm07_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm08_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm09_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm10_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm11_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm12_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm13_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm14_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm15_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm16_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm17_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm18_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm19_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm20_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm21_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm22_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm23_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm24_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm25_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm26_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm27_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm28_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm29_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm30_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers hbm31_write_base_addr    -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

set_property description {Pointer argument} [ipx::get_registers instruction_base         -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
set_property description {Pointer argument} [ipx::get_registers instruction_num          -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

# set associated_busif
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm00_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm01_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm02_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm03_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm04_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm05_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm06_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm07_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm08_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm09_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm10_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm11_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm12_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm13_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm14_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm15_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm16_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm17_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm18_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm19_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm20_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm21_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm22_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm23_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm24_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm25_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm26_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm27_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm28_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm29_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm30_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm31_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm00_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm01_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm02_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm03_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm04_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm05_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm06_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm07_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm08_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm09_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm10_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm11_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm12_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm13_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm14_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm15_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm16_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm17_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm18_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm19_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm20_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm21_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm22_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm23_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm24_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm25_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm26_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm27_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm28_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm29_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm30_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers hbm31_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]

ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers instruction_base      -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]
ipx::add_register_parameter ASSOCIATED_BUSIF [ipx::get_registers instruction_num       -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]



set_property value m00_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm00_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m01_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm01_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m02_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm02_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m03_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm03_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m04_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm04_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m05_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm05_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m06_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm06_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m07_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm07_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m08_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm08_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m09_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm09_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m10_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm10_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m11_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm11_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m12_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm12_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m13_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm13_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m14_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm14_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m15_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm15_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m16_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm16_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m17_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm17_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m18_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm18_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m19_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm19_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m20_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm20_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m21_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm21_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m22_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm22_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m23_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm23_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m24_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm24_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m25_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm25_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m26_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm26_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m27_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm27_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m28_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm28_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m29_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm29_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m30_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm30_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m31_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm31_read_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]

set_property value m00_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm00_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m01_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm01_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m02_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm02_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m03_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm03_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m04_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm04_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m05_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm05_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m06_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm06_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m07_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm07_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m08_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm08_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m09_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm09_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m10_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm10_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m11_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm11_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m12_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm12_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m13_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm13_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m14_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm14_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m15_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm15_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m16_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm16_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m17_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm17_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m18_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm18_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m19_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm19_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m20_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm20_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m21_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm21_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m22_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm22_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m23_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm23_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m24_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm24_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m25_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm25_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m26_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm26_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m27_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm27_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m28_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm28_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m29_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm29_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m30_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm30_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m31_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers hbm31_write_base_addr -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]

set_property value m00_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers instruction_base -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]
set_property value m00_axi [ipx::get_register_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_registers instruction_num -of_objects [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s_axi_control -of_objects [ipx::current_core]]]]]

ipx::add_bus_parameter FREQ_TOLERANCE_HZ [ipx::get_bus_interfaces ap_clk -of_objects [ipx::current_core]]
set_property value -1 [ipx::get_bus_parameters FREQ_TOLERANCE_HZ -of_objects [ipx::get_bus_interfaces ap_clk -of_objects [ipx::current_core]]]
set_property core_revision 2 [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::check_integrity -kernel [ipx::current_core]
ipx::save_core [ipx::current_core]

# package xo
package_xo  -xo_path ../NOP.xo -kernel_name NOP -ip_directory ./rtl_kernel/rtl_kernel.srcs/sources_1/imports/IP -ctrl_protocol user_managed

# save ip
set_property  ip_repo_paths  ./rtl_kernel/rtl_kernel.srcs/sources_1/imports/IP [current_project]
update_ip_catalog
ipx::check_integrity -quiet -kernel [ipx::current_core]
ipx::archive_core ./rtl_kernel/rtl_kernel.srcs/sources_1/imports/IP/user_NOP_1.0.zip [ipx::current_core]
exit